library identifier: 'JenkinsSharedHub@main',
        retriever: modernSCM(
            [$class:'GitSCMSource', remote:"https://github.com/Narendran3678/JenkinsSharedHub.git"]
        )
pipeline {
    agent any
    parameters {
        booleanParam(name:'deployStatus', defaultValue: false, description:'Do you want to deploy?')
    }
    environment {
        version="1.1"
        checkoutBranch="main"
        projectName="Spring-boot-jenkins-demo"
    }

    stages {
		stage("audit") {
			parallel {
                stage('audit') {
                    steps {
                        auditInfo()
                    }
                }
            }
		}

        stage("checkout") {
            steps {
                script {
                    def gitRepoUrl = "https://github.com/Narendran3678/Jenkins-Hub.git"
                    checkout([$class: 'GitSCM',
                        branches: [[name: "*/${checkoutBranch}"]],
                        userRemoteConfigs: [[url: gitRepoUrl]],
                        extensions: [
                            [$class: 'CleanBeforeCheckout'],
                            [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]
                        ]
                    ])
                }
            }
        }

        stage("Build") {
            steps {
                echo "############################# Build Stage Started ###############################"
                buildAndPackage projectName: "${projectName}"
                echo "############################# Build Stage Completed #############################"
            }
        }

        stage("Test") {
            steps {
                echo "############################# Test Stage Started ###############################"
                bat '''
                cd %projectName%
                mvn test
                '''
                echo "############################# Test Stage Completed #############################"
            }
        }

        stage("Deploy") {
            when {
                expression { return params.deployStatus }
            }
            input {
                message 'Enter Environment [1.  Prod, 2. Dev, 3. QA, 4. UAT]'
                ok 'Deploy'
                parameters {
                    string(name: 'ENVIRONMENT', defaultValue: 'Prod', description: 'Environment to Deploy')
                }
            }
            steps {
                echo "Deploying into $ENVIRONMENT"
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
            echo "Posting Test Results"
        }
        success {
            echo "Pre Process Completed Successfully."
            archiveArtifacts artifacts: 'Spring-boot-jenkins-demo/target/*.jar'
            echo "Archiving Jar Files."
        }
        failure {
            echo "PreProcess Failed"
        }
    }
}